"""empty message

Revision ID: 4d5430d614aa
Revises: 
Create Date: 2021-11-23 14:22:47.363340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5430d614aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('firstName', sa.String(length=32), nullable=False),
    sa.Column('lastName', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(length=32), nullable=False),
    sa.Column('content', sa.String(length=256), nullable=False),
    sa.Column('authorid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authorid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcementid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['announcementid'], ['announcement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('public',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcementid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['announcementid'], ['announcement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public')
    op.drop_table('local')
    op.drop_table('announcement')
    op.drop_table('user')
    # ### end Alembic commands ###
